# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Gitea
version: "1.2.0"
slug: gitea
description: Gitea
url: "https://github.com/joostlek/gitea-homeassistant-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/joostlek/{arch}-gitea-homeassistant-addon"
